baseURL = "https://andrewdyck.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hallo"
theme = "hallo-hugo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Andrew"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:andrew@andrewdyck.com"
        
    [[params.links]]
        iconset = "fas"
        icon = "newspaper"
        title = "Substack"
        url = "https://substack.com/profile/10507236-andy-dyck"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/andrewjdyck"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/andrewjdyck"
        
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/andrewjdyck/"
    
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "google-scholar"
        title = "Google Scholar"
        url = "https://scholar.google.com/citations?user=ce6O2HoAAAAJ&hl=en"
        
    [[params.links]]
        icon = "researchgate"
        title = "Research Gate"
        url = "https://www.researchgate.net/profile/Andrew-Dyck-2"
        
    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"

