baseURL = "/"
languageCode = "en-us"
title = "Andrew J. Dyck"
theme = "hugo-theme-introduction"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-2084094-1"

[params]
    author = "Andrew Dyck"
    description = "Raw data -> Analysis well-done"
    githubUsername = "andrewjdyck"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["r", "sql", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/about"
    name = "About Me"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/andrewjdyck/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/andrewjdyck/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/andrewjdyck/"
    name = "linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
