---
title: "Simulate beta distribution"
date: 2018-02-19
tags: ["R", "statistics"]
draft: true
---

```{r, warning=FALSE}
# library(dplyr)
library(ggplot2)
library(reshape2)
```


```{r}
est_alpha <- function(mu, var) {
  alpha <- (mu^2)*(((1-mu)/var) - (1/mu))
  return(alpha)
}

est_beta <- function(mu, var) {
  alpha <- (mu^2)*(((1-mu)/var) - (1/mu))
  beta <- alpha * ((1/mu) - 1)
  return(beta)
}
```

```{r}
inputs <- data.frame(
  id = c('one', 'two', 'three', 'four'),
  mean = c(0.2, 0.9, .75, .5),
  var = c(.02, .03, .001, .15),
  stringsAsFactors = FALSE
)

gen_data <- function(n, df) {
  tt <- sapply(df$id, function(x) {
    mu <- df[which(df$id == x), 'mean']
    var <- df[which(df$id == x), 'var']
    rbeta(n, est_alpha(mu, var), est_beta(mu, var))
  }, simplify = FALSE, USE.NAMES = TRUE)
  out_data <- do.call(cbind.data.frame, tt)
  return(out_data)
}

simdata <- gen_data(1000, inputs)

head(simdata)
```

```{r, warning=FALSE, message=FALSE}
plot_data <- melt(simdata)

ggplot(plot_data, aes(value, fill=variable, color=variable)) + 
  geom_density(alpha=0.1)

```


